### ISSUE TITLE
Can't install Android Studio using umake android

### ISSUE THREAD

**Issue by KelvinEC** [ubuntu/ubuntu-make#184]
I tried to install android studio using the conventional command, but it returns the error: 

ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 154, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/ui/__init__.py", line 42, in display
    cls.currentUI._display(contentType)
  File "/usr/lib/python3/dist-packages/umake/ui/cli/__init__.py", line 64, in _display
    contentType.choose(answer=input(contentType.input))
  File "/usr/lib/python3/dist-packages/umake/interactions/__init__.py", line 81, in choose
    .format(answer, txt_shortcuts, [choice.label for choice in self.choices])
KeyError: ' '

I tried to install another IDE's and it's work perfectly. 
I see another related issues, but no one solves my problem. 

Related Issue: #75

Att.

**Comment by eldarkg** [comment]
Try:
$ umake android android-studio

**Comment by didrocks** [comment]
Thanks for reporting this bug and help to make Ubuntu Make better.

I can't unfortunately reproduce that issue though. Do you mind explaining exactly what steps do you follow to get that stracktrace?
$ umake android
-> do you get the license info then? If so, what's your answer to it?

Also, knowing what LANG you are using can be useful. Maybe try LANG=C umake android to ensure it's not a translation issue.
Keep me posted! :)

**Comment by didrocks** [comment]
@eldarkg: I don't think that will fix it:
"umake android" and "umake android android-studio" are exactly the same (there is a notion of default framework for some categories, android-studio is the default one of the "android" category)

**Comment by eldarkg** [comment]
Yes :) But maybe =) 
Error -> empty key 'KeyError: ' ' '

**Comment by KelvinEC** [comment]
@didrocks  After do what you said i received the error: 
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 154, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/ui/__init__.py", line 42, in display
    cls.currentUI._display(contentType)
  File "/usr/lib/python3/dist-packages/umake/ui/cli/__init__.py", line 64, in _display
    contentType.choose(answer=input(contentType.input))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe3' in position 22: ordinal not in range(128)

**Comment by didrocks** [comment]
@KelvinEC: thanks for trying with LANG=C! you didn't fully answer to my questions though ;)
I was asking:
"Do you mind explaining exactly what steps do you follow to get that stracktrace?
$ umake android
-> do you get the license info then? If so, what's your answer to it?

Also, knowing what LANG you are using can be useful."

If you can answer those questions will help in debugging your issue! Thanks in advance!

**Comment by KelvinEC** [comment]
Yes! I run umake android, and accept the license, and appear the error!

**Comment by didrocks** [comment]
and what is your LANG in the shell?

**Comment by KelvinEC** [comment]
$locale -a  , give me that:
C
C.UTF-8
en_US.utf8
POSIX
pt_BR.utf8

**Comment by didrocks** [comment]
and `env | grep LANG`?

**Comment by KelvinEC** [comment]
LANG=pt_BR.UTF-8
GDM_LANG=pt_BR
LANGUAGE=pt_BR:pt:en

**Comment by didrocks** [comment]
Thanks a lot! I'll have a try under this settings and get back to you :)

**Comment by KelvinEC** [comment]
Thanks @didrocks.

**Comment by didrocks** [comment]
Ok, it seems the issue is that you don't have your pt_BR locale fully installed, what does:
`apt-cache policy language-pack-{gnome-,}pt`
returns? If it's not installed, I recommend installing those packages with `apt install language-pack-{gnome-,}pt`
Please confirms this is what happens here ;)

I'll add a way in Ubuntu Make to fallback to C (so, plain english) for people in your situation!

**Comment by didrocks** [comment]
And to come back to the first issue, I just pushed a commit as the pt_BR translation template was incorrect. Next release will then fix it with the new translations file shipped!

meanwhile, I suggest you use:
```
export LANG=C
export LANGUAGE=C
umake android
```
to install android studio without Ubuntu Make being translated in pt_BR. Sorry for the bother, that's why translations are important and can make program crash ;) Keep me posted that it fixed it for you!

**Comment by KelvinEC** [comment]
I installed the language packs, and try to install the android studio, and the error Persists.
After export the variables and run umake android appears to solve the problem. The IDE is installing at this moment. Thanks @didrocks.

**Comment by didrocks** [comment]
yeah, that all makes sense! This will be fixed in next release without having to fiddle the LANG* variables (I checked other translations, seems that only pt_BR had the issue).

Sorry for this issue, happy android development :)

**Comment by ipuiuna** [comment]
Hi, cant install android studio with umake, when ask for me if i accept the terms, i hit the 'a' key and dont work, but if i send 'n' to do not accept the terms work... Thanks for help

**Comment by didrocks** [comment]
Hey @ipuiuna.

Do you mind opening another bug report? Would be interesting to know what's wrong (and I think your issue is probably different from that one.

On the new bug report, do you mind:
- pasting the output of the command (your command included) so that I can see the failure
- pasting the output of `env`
- pasting your ubuntu make version with `umake --version`

Thanks!

**Comment by ipuiuna** [comment]
Hello @didrocks!
I need to change the language from portuguese Brasil to english... So the bug is with pt-br language... Thanks

**Comment by didrocks** [comment]
hey @ipuiuna!

Do you mind opening another bug report, and paste the output as requested above. Also, I need your version (see previous message) :) That will help me greatly to debug if you are running latest version or if it's another bug :)
